### ISSUE TITLE
設定ファイルをホームディレクトリ等の固定場所に置くようにしたい

### ISSUE THREAD

**Issue by tsutsui** [taka-tuos/nanotodon#10]
現状の nanotodon の仕様では `.nanotter` `.nanotter2` の設定ファイルが
nanotodon の実行ファイルと同じディレクトリにあることを想定していると思います。

しかし、汎用的に全ユーザーで使用する場合（およびパッケージシステム等に入れる場合）は
バイナリが `/usr/pkg/bin` 等の一般ユーザー書き込み不可の場所に置かれるため
複数ユーザーが設定ファイルを書き込むということができません。

同様の CUIクライアントだと以下のような感じです
tw: `~/.tw.yml` に保管
sayaka: `~/.sayaka/` 以下に各ファイルで保管

従来との互換性を考えると、起動時は
- 実行ファイルと同じ場所（もしくはカレントディレクトリ）を見る
- `~/.nanotodon/` 以下、もしくは `~/.nanotter` `~/.nanotter2` を見る

認証時は今後は `~/.nanotodon/` 以下、もしくは `~/.nanotter` `~/.nanotter2` を使う、
とすればよい？

**Comment by taka-tuos** [comment]
ディレクトリ作るのは正直めんどくさいのと、「nanotter」という呼称自体がすでに終わっている(というか認証回り使い回した結果だったと思う)ので~/.nanotodon_token(旧 .nanotter)と~/.nanotodon_domain(旧 .nanotter2) で行こうと思います

**Comment by tsutsui** [comment]
新規認証は試していませんが
既存の `.nanotter` を `~/.nanotodon_token` に、
`.nanotter2` を `~/.nanotodon_domain` にリネームした状態で接続できました。
ありがとうございます。
