### ISSUE TITLE
トゥートで改行が2つ連続した場合に改行が表示されない

### ISSUE THREAD

**Issue by tsutsui** [taka-tuos/nanotodon#9]
表題の通りで、トゥート内で改行が2つ連続している場合、 
nanotodon 上ではそれらが表示されません。
https://social.mikutter.hachune.net/@tsutsuii/103393307270448434

内部的には、改行が2つ続いた場合 ```<br>``` が連続するのではなく
markdown 的に段落区切りとして
```html
<p>nanotodon</p><p>改行が2つ続くと消えちゃう感</p>
```
という感じになっているようなので、そこをハンドリングしないといけないっぽいです

**Comment by taka-tuos** [comment]
とりあえず二個目以降の<p>で2回改行するようにしてみます

**Comment by tsutsui** [comment]
テストOKです。ありがとうございます
![nanotodon-issue-9](https://user-images.githubusercontent.com/3054480/71640801-753f6800-2cd4-11ea-8e0a-bfe06becbc4e.png)
